# Generated by Django 3.1.3 on 2020-12-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CherryPickingPicture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-id']},
        ),
    ]
